#!/bin/bash

mvn package && cp target/OtherAnimalTeleport2.0.jar /srv/craft/plugins/OtherAnimalTeleport2.0.jar && { printf "username\npassword\nNOLOG\npm reload OtherAnimalTeleport\n" | nc -q 0 localhost 25564; }
